name: Daily Backend Tests

on:
  push:
  pull_request:
  schedule:
    # GitHub Actions uses UTC. 07:00 UTC equals 08:00 CET (germantime)
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest #windows-latest works too

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest TESTS -v
